<a href="https://colab.research.google.com/github/LucioJuniorMachado/API/blob/main/API_TV_SHOW.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Site utilizado

In [ ]:
#http://www.omdbapi.com/

Instalando a API

In [30]:
!pip install omdb

Requirement already satisfied: omdb in /usr/local/lib/python3.11/dist-packages (0.10.1)
Requirement already satisfied: requests>=2.0.1 in /usr/local/lib/python3.11/dist-packages (from omdb) (2.32.3)
Requirement already satisfied: charset-normalizer<4,>=2 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.1->omdb) (3.4.1)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.1->omdb) (3.10)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.1->omdb) (2.3.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.11/dist-packages (from requests>=2.0.1->omdb) (2025.1.31)

Criei o token no site da API

In [6]:
# Colocar token criado aqui:
TOkEN = "c9c0a86f"

Dando uma olhada na série Severance e imprimindo as informações

In [24]:
import requests

# Correct API key (replace with your valid API key)
api_key = "c9c0a86f"  # Verify your key at https://www.omdbapi.com/

# Movie title to search for
movie_title = "Severance"  # Replace with the desired movie title
import requests

# Correct API key (replace with your valid API key)
api_key = "c9c0a86f"  # Verify your key at https://www.omdbapi.com/

# Movie title to search for
movie_title = "Severance"  # Replace with the desired movie title

# Construct the URL
movie_url = f"http://www.omdbapi.com/?apikey={api_key}&t={movie_title}"

# Make the request to the API
response = requests.get(movie_url)

# Debugging: Print the full URL and status code for investigation
print(f"Request URL: {movie_url}")
print(f"HTTP Status Code: {response.status_code}")

# Handle the response
if response.status_code == 200:
    movie_data = response.json()
    if movie_data.get("Response") == "True":
        print("Movie Information:")
        print(movie_data)
    else:
        print("Error:", movie_data.get("Error"))
elif response.status_code == 401:
    print("Unauthorized access. Please check your API key.")
else:
    print("Failed to fetch data. HTTP Status Code:", response.status_code)
response = requests.get(movie_url)

Request URL: http://www.omdbapi.com/?apikey=c9c0a86f&t=Severance
HTTP Status Code: 200
Movie Information:
{'Title': 'Severance', 'Year': '2022–', 'Rated': 'TV-MA', 'Released': '18 Feb 2022', 'Runtime': 'N/A', 'Genre': 'Drama, Mystery, Sci-Fi', 'Director': 'N/A', 'Writer': 'Dan Erickson', 'Actors': 'Adam Scott, Zach Cherry, Britt Lower', 'Plot': 'Mark leads a team of office workers whose memories have been surgically divided between their work and personal lives. When a mysterious colleague appears outside of work, it begins a journey to discover the truth about their jobs.', 'Language': 'English', 'Country': 'United States', 'Awards': 'Won 2 Primetime Emmys. 28 wins & 104 nominations total', 'Poster': 'https://m.media-amazon.com/images/M/MV5BZDI5YzJhODQtMzQyNy00YWNmLWIxMjUtNDBjNjA5YWRjMzExXkEyXkFqcGc@._V1_SX300.jpg', 'Ratings': [{'Source': 'Internet Movie Database', 'Value': '8.7/10'}], 'Metascore': 'N/A', 'imdbRating': '8.7', 'imdbVotes': '239,196', 'imdbID': 'tt11280740', 'Type': 'series', 'totalSeasons': '2', 'Response': 'True'}

Criando e organizando um data frame e visualizando as colunas "Category" e "Information"

In [8]:
import requests
import pandas as pd

# Correct API key (replace with your valid API key)
api_key = "c9c0a86f"  # Verify your key at https://www.omdbapi.com/

# Movie title to search for
movie_title = "Severance"  # Replace with the desired movie title

# Construct the URL
movie_url = f"http://www.omdbapi.com/?apikey={api_key}&t={movie_title}"

# Make the request to the API
response = requests.get(movie_url)

# Handle the response
if response.status_code == 200:
    movie_data = response.json()
    if movie_data.get("Response") == "True":
        # Create a DataFrame from the movie data
        df = pd.DataFrame([movie_data])

        # Organize the DataFrame (transpose for better readability)
        df = df.transpose()

        # Reset the index to have a proper column name
        df = df.reset_index()
        df.columns = ["Category", "Information"]

        print(df)

    else:
        print("Error:", movie_data.get("Error"))
else:
    print("Failed to fetch data. HTTP Status Code:", response.status_code)

        Category                                        Information
0          Title                                          Severance
1           Year                                              2022–
2          Rated                                              TV-MA
3       Released                                        18 Feb 2022
4        Runtime                                                N/A
5          Genre                             Drama, Mystery, Sci-Fi
6       Director                                                N/A
7         Writer                                       Dan Erickson
8         Actors               Adam Scott, Zach Cherry, Britt Lower
9           Plot  Mark leads a team of office workers whose memo...
10      Language                                            English
11       Country                                      United States
12        Awards  Won 2 Primetime Emmys. 28 wins & 104 nominatio...
13        Poster  https://m.media-amazon.com/images/M/MV5BZDI5Yz...
14       Ratings  [{'Source': 'Internet Movie Database', 'Value'...
15     Metascore                                                N/A
16    imdbRating                                                8.7
17     imdbVotes                                            239,196
18        imdbID                                         tt11280740
19          Type                                             series
20  totalSeasons                                                  2
21      Response                                               True

Crie um pivotamento com 5 colunas "title", "year", "writer", "language" e "country"

In [25]:
import pandas as pd

# Assuming 'df' from the previous code is available and contains the movie data
# If not, replace this with the code to create the DataFrame 'df'

# Extract relevant columns (handling potential missing values)
title = df.loc[df["Category"] == "Title", "Information"].values[0] if "Title" in df["Category"].values else "N/A"
year = df.loc[df["Category"] == "Year", "Information"].values[0] if "Year" in df["Category"].values else "N/A"
writer = df.loc[df["Category"] == "Writer", "Information"].values[0] if "Writer" in df["Category"].values else "N/A"
language = df.loc[df["Category"] == "Language", "Information"].values[0] if "Language" in df["Category"].values else "N/A"
country = df.loc[df["Category"] == "Country", "Information"].values[0] if "Country" in df["Category"].values else "N/A"


# Create the new DataFrame for pivoting
pivot_data = {'title': [title], 'year': [year], 'writer': [writer], 'language': [language], 'country': [country]}
pivot_df = pd.DataFrame(pivot_data)

pivot_df

       title   year        writer language        country
0  Severance  2022–  Dan Erickson  English  United States

Ordenei o dataframe com os atributos "title", "writer" e "country"

In [29]:
ordered_df = pivot_df.sort_values(by=['title', 'writer', 'country'])

ordered_df

       title   year        writer language        country
0  Severance  2022–  Dan Erickson  English  United States

Filtrei apenas "Title" e "Writer"

In [12]:
import requests
import pandas as pd

# Correct API key (replace with your valid API key)
api_key = "c9c0a86f"  # Verify your key at https://www.omdbapi.com/

# Movie title to search for
movie_title = "Severance"  # Replace with the desired movie title

# Construct the URL
movie_url = f"http://www.omdbapi.com/?apikey={api_key}&t={movie_title}"

# Make the request to the API
response = requests.get(movie_url)

# Handle the response
if response.status_code == 200:
    movie_data = response.json()
    if movie_data.get("Response") == "True":
        # Create a DataFrame from the movie data
        df = pd.DataFrame([movie_data])

        # Organize the DataFrame (transpose for better readability)
        df = df.transpose()

        # Reset the index to have a proper column name
        df = df.reset_index()
        df.columns = ["Category", "Information"]

        # Extract title and director, handling potential missing values
        title = df.loc[df["Category"] == "Title", "Information"].values[0] if "Title" in df["Category"].values else "N/A"
        director = df.loc[df["Category"] == "Writer", "Information"].values[0] if "Writer" in df["Category"].values else "N/A"

        # Create a new DataFrame with only title and director
        filtered_df = pd.DataFrame({'Title': [title], 'Writer': [writer]})
        print(filtered_df)

    else:
        print("Error:", movie_data.get("Error"))
else:
    print("Failed to fetch data. HTTP Status Code:", response.status_code)

       Title        Writer
0  Severance  Dan Erickson

Fiz uma busca no site pela palavras em inglês "arms", um loop para percorrer os resultados e imprimi.

In [21]:
import json
from omdb import OMDBClient

# Correct API key (replace with your valid API key)
api_key = "c9c0a86f"  # Verify your key at https://www.omdbapi.com/

# Movie title to search for -  searching for "arms" now
movie_title = "arms"  # Replace with the desired movie title

# Construct the URL
movie_url = f"http://www.omdbapi.com/?apikey={api_key}&s={movie_title}&page=1" #Using 's' parameter for search

# Lista para armazenar os dados dos filmes
filmes = []

# Loop para percorrer as páginas de resultados
page = 1
while True:
    response = requests.get(movie_url.format(page))
    data = response.json()

    if 'Search' in data and data['Search']:  # Check for valid search results
        filmes.extend(data['Search'])
        page +=1
        movie_url = f"http://www.omdbapi.com/?apikey={api_key}&s={movie_title}&page={page}" #Update URL for next page
    elif 'Error' in data and data['Error'] == "Too many results.":
        print("Too many results. Showing the first 10.")
        break # Stop the loop to prevent indefinite execution

    else:
        # Exit the loop if no more results are found
        break

# Criação do DataFrame
df_filmes = pd.DataFrame(filmes)
df_filmes

,Title,Year,imdbID,Type,Poster
0,Shoulder Arms,1918,tt0009611,movie,https://m.media-amazon.com/images/M/MV5BODQ0Mz...
1,A Farewell to Arms,1932,tt0022879,movie,https://m.media-amazon.com/images/M/MV5BMzM2OD...
2,Babylon 5: A Call to Arms,1999,tt0146455,movie,https://m.media-amazon.com/images/M/MV5BYjg5OD...
3,With Open Arms,2017,tt5804948,movie,https://m.media-amazon.com/images/M/MV5BYmQ0OD...
4,To Write Love on Her Arms,2012,tt1850418,movie,https://m.media-amazon.com/images/M/MV5BMjA2Nz...
...,...,...,...,...,...
404,Gozo at Arms,2018,tt7396162,movie,https://m.media-amazon.com/images/M/MV5BNmJlMD...
405,Empty Arms,2007,tt7414534,movie,N/A
406,JN1: A Call for Arms,2000,tt7504594,movie,N/A
407,To the Arms of a Neon Light,2016,tt7580906,movie,https://m.media-amazon.com/images/M/MV5BNjQ3Zj...
408,In Your Arms Steve Brosky,2017,tt7759186,movie,https://m.media-amazon.com/images/M/MV5BMTA1NT...